apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-alertmanager.rules
  namespace: monitoring
  labels:
    rule-type: "alerting"
    prometheus: main
spec:
  groups:
  - name: alertmanager.rules
    rules:
    - alert: AlertmanagerFailedReload
      annotations:
        description: ddd
        link: dd
        summary: dd
      expr: |-
        absent(nonexistent{cluster="abs"}) == 1
      for: 15s
      labels:
        severity: critical
        namespace: monitoring
        class: non-live
        app: new
