apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: monitoring
type: Opaque
data:
  url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzNzVQOVM2NjUvQjA0Nkg0UDZVUjMvc0E5dnNWSlZvTnhtV3lRRVU0YVZmQzBN
